import 'package:projeto_biblas/database/modules/menu_cascata/construtorBlocos.dart';

final cursosData = <ConstrutorBlocos>[
  const ConstrutorBlocos(titulo: 'Administração', blocos: [
    ConstrutorBlocos(titulo: 'Primeiro ano', blocos: [
      ConstrutorBlocos(titulo: 'Comunicação Empresarial'),
      ConstrutorBlocos(titulo: 'Inovação e Novas Abordagens'),
      ConstrutorBlocos(titulo: 'Simulação Empresarial'),
      ConstrutorBlocos(titulo: 'Sociologia Política e Organizacional'),
      ConstrutorBlocos(titulo: 'Teoria Geral dos Sistemas'),
    ]),
    ConstrutorBlocos(titulo: 'Segundo ano', blocos: [
      ConstrutorBlocos(titulo: 'Contabilidade Gerencial'),
      ConstrutorBlocos(titulo: 'Economia'),
      ConstrutorBlocos(titulo: 'Economia Aplicada'),
      ConstrutorBlocos(titulo: 'Estatística'),
      ConstrutorBlocos(titulo: 'Estatística Aplicada à Administração'),
      ConstrutorBlocos(titulo: 'Finanças Empresariais'),
      ConstrutorBlocos(
          titulo: 'Gestão de Materiais e Administração de Compras'),
      ConstrutorBlocos(titulo: 'Gestão de Pessoas'),
      ConstrutorBlocos(titulo: 'Marketing'),
      ConstrutorBlocos(titulo: 'Matemática Financeira'),
    ]),
    ConstrutorBlocos(titulo: 'Terceiro ano', blocos: [
      ConstrutorBlocos(titulo: 'Comércio Exterior'),
      ConstrutorBlocos(titulo: 'Gestão da Produção'),
      ConstrutorBlocos(titulo: 'Gestão Financeira'),
      ConstrutorBlocos(titulo: 'Marketing Avançado'),
      ConstrutorBlocos(titulo: 'Métodos Quantitativos'),
      ConstrutorBlocos(titulo: 'Planejamento da Produção'),
      ConstrutorBlocos(titulo: 'Planejamento de Marketing para Negócios'),
      ConstrutorBlocos(titulo: 'Projeto de Pesquisa'),
      ConstrutorBlocos(titulo: 'Projetos de Investimentos e Empreendedorismo'),
      ConstrutorBlocos(titulo: 'Relações Jurídicas Empresariais'),
    ]),
    ConstrutorBlocos(titulo: 'Quarto ano', blocos: [
      ConstrutorBlocos(titulo: 'Economia e Negócios Internacionais'),
      ConstrutorBlocos(titulo: 'Gestão de Cadeia de Suprimentos'),
      ConstrutorBlocos(titulo: 'Inovação e Novas Abordagens em Administração'),
      ConstrutorBlocos(titulo: 'Planejamento Estratégico e Sustentabilidade'),
      ConstrutorBlocos(titulo: 'Simulação Empresarial-Jogos de Empresa'),
      ConstrutorBlocos(titulo: 'Trabalho de Conclusão de Curso I'),
      ConstrutorBlocos(titulo: 'Trabalho de Conclusão de Curso II'),
    ]),
  ]),
  const ConstrutorBlocos(titulo: 'Ciência da Computação', blocos: [
    ConstrutorBlocos(titulo: 'Banco de Dados Relacionais'),
    ConstrutorBlocos(titulo: 'Lógica de Programação'),
    ConstrutorBlocos(titulo: 'Modelagem Orientada a Objetos'),
    ConstrutorBlocos(titulo: 'Programação Orientada a Objetos'),
    ConstrutorBlocos(titulo: 'Projeto Integrado Interdisciplinar'),
  ]),
  const ConstrutorBlocos(titulo: 'Design', blocos: [
    ConstrutorBlocos(titulo: 'Primeiro ano', blocos: [
      ConstrutorBlocos(titulo: 'Criação Bidimensional'),
      ConstrutorBlocos(titulo: 'Desenho'),
      ConstrutorBlocos(titulo: 'Desenho Técnico'),
      ConstrutorBlocos(titulo: 'Design e Conhecimento'),
      ConstrutorBlocos(titulo: 'Edição de Imagens Digitais'),
      ConstrutorBlocos(titulo: 'Fundamentos de Design'),
    ]),
    ConstrutorBlocos(titulo: 'Segundo ano', blocos: [
      ConstrutorBlocos(titulo: 'Design e História'),
      ConstrutorBlocos(titulo: 'Design e Sociedade'),
      ConstrutorBlocos(titulo: 'Design Emocional'),
      ConstrutorBlocos(titulo: 'Estudos e Pesquisas Mercadológicas'),
      ConstrutorBlocos(titulo: 'Ilustração'),
      ConstrutorBlocos(titulo: 'Ilustração Digital'),
      ConstrutorBlocos(titulo: 'Marketing'),
      ConstrutorBlocos(titulo: 'Materiais Poliméricos'),
      ConstrutorBlocos(titulo: 'Metadesign'),
      ConstrutorBlocos(titulo: 'Modelagem 3D em Superfícies'),
      ConstrutorBlocos(titulo: 'Modelagem 3D Paramétrica'),
      ConstrutorBlocos(titulo: 'Sistemas Elétricos e Mecânicos'),
    ]),
    ConstrutorBlocos(titulo: 'Terceiro ano', blocos: [
      ConstrutorBlocos(titulo: 'Cool Hunting'),
      ConstrutorBlocos(titulo: 'Design de Superfície'),
      ConstrutorBlocos(titulo: 'Design Gráfico'),
      ConstrutorBlocos(titulo: 'Design Sistêmico'),
      ConstrutorBlocos(titulo: 'Design Studio'),
      ConstrutorBlocos(titulo: 'Ergonomia Cognitiva'),
      ConstrutorBlocos(titulo: 'Ergonomia Física'),
      ConstrutorBlocos(titulo: 'Materiais Compósitos'),
      ConstrutorBlocos(titulo: 'Materiais Metálicos'),
      ConstrutorBlocos(titulo: 'Metodologia de Pesquisa I'),
      ConstrutorBlocos(titulo: 'Modelagem 3D Poligonal'),
      ConstrutorBlocos(titulo: 'Modelagem Digital'),
    ]),
    ConstrutorBlocos(titulo: 'Quarto ano', blocos: [
      ConstrutorBlocos(titulo: 'Branding'),
      ConstrutorBlocos(titulo: 'Gerenciamento de Projeto'),
      ConstrutorBlocos(titulo: 'Metodologia da Pesquisa II'),
      ConstrutorBlocos(titulo: 'Metodologia de Pesquisa III'),
      ConstrutorBlocos(titulo: 'Modelos e Ambientes Virtuais'),
      ConstrutorBlocos(titulo: 'Modelos e Protótipos'),
      ConstrutorBlocos(titulo: 'Projeto de Produtos'),
      ConstrutorBlocos(titulo: 'Tópicos Avançados em Design'),
      ConstrutorBlocos(titulo: 'Trabalho de Conclusão de Curso I'),
      ConstrutorBlocos(titulo: 'Trabalho de Conclusão de Curso II'),
    ]),
  ]),
  const ConstrutorBlocos(titulo: 'Engenharia', blocos: [
    ConstrutorBlocos(titulo: 'Ciclo Básico', blocos: [
      ConstrutorBlocos(titulo: 'Algoritmos e Programação'),
      ConstrutorBlocos(titulo: 'Cálculo Diferencial e Integral I'),
      ConstrutorBlocos(titulo: 'Desenho'),
      ConstrutorBlocos(titulo: 'Física I'),
      ConstrutorBlocos(titulo: 'Fundamentos de Engenharia'),
      ConstrutorBlocos(titulo: 'Química Geral'),
      ConstrutorBlocos(titulo: 'Vetores, Curvas e Superfícies'),
    ]),
    ConstrutorBlocos(titulo: 'Alimentos', blocos: [
      ConstrutorBlocos(titulo: 'Cálculo Diferencial e Integral II'),
      ConstrutorBlocos(titulo: 'Estatística'),
      ConstrutorBlocos(titulo: 'Física II'),
      ConstrutorBlocos(
          titulo: 'Fundamentos de Engenharia de Processos e Termodinâmica'),
      ConstrutorBlocos(titulo: 'Matemática Computacional'),
      ConstrutorBlocos(titulo: 'Mecânica Geral'),
      ConstrutorBlocos(titulo: 'Química Aplicada I'),
    ]),
    ConstrutorBlocos(titulo: 'Civil', blocos: [
      ConstrutorBlocos(
          titulo: 'Arquitetura das Edificações e Desenho Universal'),
      ConstrutorBlocos(titulo: 'Cálculo Diferencial e Integral II'),
      ConstrutorBlocos(titulo: 'Física II'),
      ConstrutorBlocos(titulo: 'Geologia de Engenharia e Ambiental'),
      ConstrutorBlocos(titulo: 'Matemática Computacional'),
      ConstrutorBlocos(titulo: 'Mecânica Geral'),
      ConstrutorBlocos(titulo: 'Representações Gráficas'),
      ConstrutorBlocos(titulo: 'Resistência dos Materiais I'),
      ConstrutorBlocos(titulo: 'Topografia e Geomática'),
    ]),
    ConstrutorBlocos(titulo: 'Computação', blocos: [
      ConstrutorBlocos(titulo: 'Cálculo Diferencial e Integral II'),
      ConstrutorBlocos(titulo: 'Estrutura de Dados e Técnicas de Programação'),
      ConstrutorBlocos(titulo: 'Fenômenos de Transporte'),
      ConstrutorBlocos(titulo: 'Física II'),
      ConstrutorBlocos(titulo: 'Fundamentos de Circuitos Digitais'),
      ConstrutorBlocos(titulo: 'Fundamentos de Circuitos Analógicos'),
      ConstrutorBlocos(titulo: 'Matemática Computacional'),
      ConstrutorBlocos(titulo: 'Mecânica Geral'),
      ConstrutorBlocos(titulo: 'Resistência dos Materiais'),
    ]),
    ConstrutorBlocos(titulo: 'Controle e Automação', blocos: [
      ConstrutorBlocos(titulo: 'Cálculo Diferencial e Integral II'),
      ConstrutorBlocos(titulo: 'Estrutura de Dados e Técnicas de Programação'),
      ConstrutorBlocos(titulo: 'Fenômenos de Transporte'),
      ConstrutorBlocos(titulo: 'Física II'),
      ConstrutorBlocos(titulo: 'Fundamentos de Circuitos Digitais'),
      ConstrutorBlocos(titulo: 'Fundamentos de Circuitos Analógicos'),
      ConstrutorBlocos(titulo: 'Matemática Computacional'),
      ConstrutorBlocos(titulo: 'Mecânica Geral'),
      ConstrutorBlocos(titulo: 'Resistência dos Materiais'),
    ]),
    ConstrutorBlocos(titulo: 'Eletrônica', blocos: [
      ConstrutorBlocos(titulo: 'Cálculo Diferencial e Integral II'),
      ConstrutorBlocos(titulo: 'Estrutura de Dados e Técnicas de Programação'),
      ConstrutorBlocos(titulo: 'Fenômenos de Transporte'),
      ConstrutorBlocos(titulo: 'Física II'),
      ConstrutorBlocos(titulo: 'Fundamentos de Circuitos Digitais'),
      ConstrutorBlocos(titulo: 'Fundamentos de Circuitos Analógicos'),
      ConstrutorBlocos(titulo: 'Matemática Computacional'),
      ConstrutorBlocos(titulo: 'Mecânica Geral'),
      ConstrutorBlocos(titulo: 'Resistência dos Materiais'),
    ]),
    ConstrutorBlocos(titulo: 'Elétrica', blocos: [
      ConstrutorBlocos(titulo: 'Cálculo Diferencial e Integral II'),
      ConstrutorBlocos(titulo: 'Estrutura de Dados e Técnicas de Programação'),
      ConstrutorBlocos(titulo: 'Fenômenos de Transporte'),
      ConstrutorBlocos(titulo: 'Física II'),
      ConstrutorBlocos(titulo: 'Fundamentos de Circuitos Digitais'),
      ConstrutorBlocos(titulo: 'Fundamentos de Circuitos Analógicos'),
      ConstrutorBlocos(titulo: 'Matemática Computacional'),
      ConstrutorBlocos(titulo: 'Mecânica Geral'),
      ConstrutorBlocos(titulo: 'Resistência dos Materiais'),
    ]),
    ConstrutorBlocos(titulo: 'Mecânica', blocos: [
      ConstrutorBlocos(titulo: 'Cálculo Diferencial e Integral II'),
      ConstrutorBlocos(titulo: 'Estatística'),
      ConstrutorBlocos(titulo: 'Física II'),
      ConstrutorBlocos(titulo: 'Introdução a Projeto e Manufatura'),
      ConstrutorBlocos(titulo: 'Matemática Computacional'),
      ConstrutorBlocos(titulo: 'Materiais de Construção Mecânica I'),
      ConstrutorBlocos(titulo: 'Mecânica Geral'),
      ConstrutorBlocos(titulo: 'Resistência dos Materiais'),
    ]),
    ConstrutorBlocos(titulo: 'Produção', blocos: [
      ConstrutorBlocos(titulo: 'Cálculo Diferencial e Integral II'),
      ConstrutorBlocos(titulo: 'Ciências Térmicas I'),
      ConstrutorBlocos(titulo: 'Física II'),
      ConstrutorBlocos(titulo: 'Introdução à Engenharia de Produção'),
      ConstrutorBlocos(titulo: 'Matemática Computacional'),
      ConstrutorBlocos(titulo: 'Materiais de Construção Mecânica I'),
      ConstrutorBlocos(titulo: 'Mecânica Geral'),
      ConstrutorBlocos(titulo: 'Resistência dos Materiais'),
      ConstrutorBlocos(titulo: 'Sistemas de Informação I'),
    ]),
    ConstrutorBlocos(titulo: 'Química', blocos: [
      ConstrutorBlocos(titulo: 'Cálculo Diferencial e Integral II'),
      ConstrutorBlocos(titulo: 'Estatística'),
      ConstrutorBlocos(titulo: 'Física II'),
      ConstrutorBlocos(
          titulo: 'Fundamentos de Engenharia de Processos e Termodinâmica'),
      ConstrutorBlocos(titulo: 'Matemática Computacional'),
      ConstrutorBlocos(titulo: 'Mecânica Geral'),
      ConstrutorBlocos(titulo: 'Química Aplicada I'),
    ]),
  ]),
  const ConstrutorBlocos(titulo: 'Sistema de Informação', blocos: [
    ConstrutorBlocos(titulo: 'Banco de Dados Relacionais'),
    ConstrutorBlocos(titulo: 'Lógica de Programação'),
    ConstrutorBlocos(titulo: 'Modelagem Orientada a Objetos'),
    ConstrutorBlocos(titulo: 'Programação Orientada a Objetos'),
    ConstrutorBlocos(titulo: 'Projeto Integrado Interdisciplinar'),
  ])
];
